language: go

before_install:
  - if [ "TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get -y install libxml2-dev libxslt1-dev liblzma-dev zlib1g-dev; fi
  - if [ "TRAVIS_OS_NAME" = "freebsd" ]; then pkg install -y libxml2 libxslt; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install libxml2 libxslt; fi

os:
  - linux
  - freebsd
  - osx

compiler:
  - gcc
  - clang

go_import_path: github.com/wamuir/go-xslt

go:
  - 1.13.x
  - 1.14.x
  - 1.15.x
  - 1.16.x
  - tip

script:
     - go test -coverprofile=coverage.txt -covermode=atomic ./...

after_success:
     - bash <(curl -s https://codecov.io/bash)
